# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NTkzNWMzNDUwMGVjOTI1NDk4YjgxYWEzMWI1YTUxMjEwNGJkY2IwYWM4ZjRhMTJjMTIxZjEyMzM1ODg5ZjUxZjI4NGU3NTIyZGIxMWIwNmJlZTQ4NmExZTM4MjViM2M2NzYzMjVlMDkyZmQxZDA3YmI5NDRjMzIwNzg2MGQxYmU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
